# Generated by Django 3.2.18 on 2023-03-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_Date',
            new_name='published_date',
        ),
    ]
